// Generated by pnpm gen. Do not edit.
import { contextBridge, ipcRenderer } from 'electron';
import type { FrBridge, FrEvent } from '../renderer/ipc/client.generated';
import { AppError } from '@freeread/core';
import type { FrEventName } from '@freeread/core';
const events: readonly string[] = ["fr:parser:progress","fr:parser:failed","fr:translate:progress","fr:library:changed","fr:notes:changed","fr:app:updateAvailable","fr:agent:event","fr:project:changed"];
const bridge: FrBridge = {
  local: { pickPdf: () => ipcRenderer.invoke('fr-local:pickPdf'), cancelImport: () => ipcRenderer.invoke('fr-local:cancelImport') },
  library: {
    list: (req) => ipcRenderer.invoke('fr:library:list', req),
    get: (req) => ipcRenderer.invoke('fr:library:get', req),
    import: (req) => ipcRenderer.invoke('fr:library:import', req),
    importFolder: (req) => ipcRenderer.invoke('fr:library:importFolder', req),
    remove: (req) => ipcRenderer.invoke('fr:library:remove', req),
    rename: (req) => ipcRenderer.invoke('fr:library:rename', req),
    updateMeta: (req) => ipcRenderer.invoke('fr:library:updateMeta', req),
    reindex: (req) => ipcRenderer.invoke('fr:library:reindex', req),
    listTags: (req) => ipcRenderer.invoke('fr:library:listTags', req),
    setTags: (req) => ipcRenderer.invoke('fr:library:setTags', req),
  },
  doc: {
    open: (req) => ipcRenderer.invoke('fr:doc:open', req),
    close: (req) => ipcRenderer.invoke('fr:doc:close', req),
    getAnchorModel: (req) => ipcRenderer.invoke('fr:doc:getAnchorModel', req),
    getPageBitmap: (req) => ipcRenderer.invoke('fr:doc:getPageBitmap', req),
    exportPatch: (req) => ipcRenderer.invoke('fr:doc:exportPatch', req),
    applyPatch: (req) => ipcRenderer.invoke('fr:doc:applyPatch', req),
    search: (req) => ipcRenderer.invoke('fr:doc:search', req),
  },
  parser: {
    start: (req) => ipcRenderer.invoke('fr:parser:start', req),
    cancel: (req) => ipcRenderer.invoke('fr:parser:cancel', req),
    health: (req) => ipcRenderer.invoke('fr:parser:health', req),
    listEngines: (req) => ipcRenderer.invoke('fr:parser:listEngines', req),
    consentModelDownload: (req) => ipcRenderer.invoke('fr:parser:consentModelDownload', req),
  },
  notes: {
    list: (req) => ipcRenderer.invoke('fr:notes:list', req),
    upsert: (req) => ipcRenderer.invoke('fr:notes:upsert', req),
    delete: (req) => ipcRenderer.invoke('fr:notes:delete', req),
    exportMarkdown: (req) => ipcRenderer.invoke('fr:notes:exportMarkdown', req),
    importMarkdown: (req) => ipcRenderer.invoke('fr:notes:importMarkdown', req),
    updateProgress: (req) => ipcRenderer.invoke('fr:notes:updateProgress', req),
  },
  translate: {
    translateUnits: (req) => ipcRenderer.invoke('fr:translate:translateUnits', req),
    cancel: (req) => ipcRenderer.invoke('fr:translate:cancel', req),
    getCache: (req) => ipcRenderer.invoke('fr:translate:getCache', req),
    clearCache: (req) => ipcRenderer.invoke('fr:translate:clearCache', req),
    listProviders: (req) => ipcRenderer.invoke('fr:translate:listProviders', req),
    testProvider: (req) => ipcRenderer.invoke('fr:translate:testProvider', req),
    listGlossary: (req) => ipcRenderer.invoke('fr:translate:listGlossary', req),
    upsertGlossary: (req) => ipcRenderer.invoke('fr:translate:upsertGlossary', req),
    deleteGlossary: (req) => ipcRenderer.invoke('fr:translate:deleteGlossary', req),
  },
  fetch: {
    resolveMetadata: (req) => ipcRenderer.invoke('fr:fetch:resolveMetadata', req),
    fetchOpenAccess: (req) => ipcRenderer.invoke('fr:fetch:fetchOpenAccess', req),
    listProviders: (req) => ipcRenderer.invoke('fr:fetch:listProviders', req),
    auditLog: (req) => ipcRenderer.invoke('fr:fetch:auditLog', req),
  },
  zotero: {
    detect: (req) => ipcRenderer.invoke('fr:zotero:detect', req),
    listCollections: (req) => ipcRenderer.invoke('fr:zotero:listCollections', req),
    importSelection: (req) => ipcRenderer.invoke('fr:zotero:importSelection', req),
    status: (req) => ipcRenderer.invoke('fr:zotero:status', req),
  },
  app: {
    getConfig: (req) => ipcRenderer.invoke('fr:app:getConfig', req),
    setConfig: (req) => ipcRenderer.invoke('fr:app:setConfig', req),
    getVersion: (req) => ipcRenderer.invoke('fr:app:getVersion', req),
    checkUpdate: (req) => ipcRenderer.invoke('fr:app:checkUpdate', req),
    openExternal: (req) => ipcRenderer.invoke('fr:app:openExternal', req),
    exportLogs: (req) => ipcRenderer.invoke('fr:app:exportLogs', req),
    getCacheInfo: (req) => ipcRenderer.invoke('fr:app:getCacheInfo', req),
    clearCache: (req) => ipcRenderer.invoke('fr:app:clearCache', req),
    doctor: (req) => ipcRenderer.invoke('fr:app:doctor', req),
    getCapabilities: (req) => ipcRenderer.invoke('fr:app:getCapabilities', req),
    getApiVersion: (req) => ipcRenderer.invoke('fr:app:getApiVersion', req),
  },
  window: {
    openReaderTab: (req) => ipcRenderer.invoke('fr:window:openReaderTab', req),
    closeTab: (req) => ipcRenderer.invoke('fr:window:closeTab', req),
    focusMain: (req) => ipcRenderer.invoke('fr:window:focusMain', req),
  },
  agent: {
    start: (req) => ipcRenderer.invoke('fr:agent:start', req),
    send: (req) => ipcRenderer.invoke('fr:agent:send', req),
    cancel: (req) => ipcRenderer.invoke('fr:agent:cancel', req),
    listSessions: (req) => ipcRenderer.invoke('fr:agent:listSessions', req),
    getSession: (req) => ipcRenderer.invoke('fr:agent:getSession', req),
    deleteSession: (req) => ipcRenderer.invoke('fr:agent:deleteSession', req),
    listTools: (req) => ipcRenderer.invoke('fr:agent:listTools', req),
    setPermissionRule: (req) => ipcRenderer.invoke('fr:agent:setPermissionRule', req),
    listSkills: (req) => ipcRenderer.invoke('fr:agent:listSkills', req),
    installSkill: (req) => ipcRenderer.invoke('fr:agent:installSkill', req),
  },
  project: {
    ensure: (req) => ipcRenderer.invoke('fr:project:ensure', req),
    getPermissions: (req) => ipcRenderer.invoke('fr:project:getPermissions', req),
    listFiles: (req) => ipcRenderer.invoke('fr:project:listFiles', req),
    importFiles: (req) => ipcRenderer.invoke('fr:project:importFiles', req),
    exportZip: (req) => ipcRenderer.invoke('fr:project:exportZip', req),
  },
  on<T extends FrEventName>(type: T, handler: (event: FrEvent<T>) => void) {
    if (!events.includes(type)) throw new AppError('FR-IPC-001', { category: 'ipc', severity: 'fatal', retryable: false, i18nKey: 'errors.FR-IPC-001' });
    const listener = (_event: unknown, data: FrEvent<T>) => handler(data);
    ipcRenderer.on(type, listener);
    return () => { ipcRenderer.removeListener(type, listener); };
  },
};
contextBridge.exposeInMainWorld('fr', bridge);
