// Generated by pnpm gen. Do not edit.
export const CHANNEL_REGISTRY = [
  {
    "name": "fr:library:list",
    "domain": "library",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "分页查询文献库条目（标题/摘要/正文 FTS5 检索 + 标签过滤）",
    "request": {
      "$ref": "#/$defs/LibraryListRequest"
    },
    "response": {
      "$ref": "#/$defs/LibraryListResponse"
    },
    "errors": [],
    "since": 1
  },
  {
    "name": "fr:library:get",
    "domain": "library",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "按 docId 或 citekey 取单个条目（二者恰好提供一个）",
    "request": {
      "$ref": "#/$defs/LibraryGetRequest"
    },
    "response": {
      "$ref": "#/$defs/LibraryGetResponse"
    },
    "errors": [
      "FR-LIB-005"
    ],
    "since": 1
  },
  {
    "name": "fr:library:import",
    "domain": "library",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "从本地绝对路径或白名单 URL 导入一篇 PDF（sha256 去重，重复导入不是错误）",
    "request": {
      "$ref": "#/$defs/LibraryImportRequest"
    },
    "response": {
      "$ref": "#/$defs/LibraryImportResponse"
    },
    "errors": [
      "FR-LIB-001",
      "FR-LIB-002",
      "FR-LIB-004",
      "FR-LIB-007",
      "FR-LIB-009",
      "FR-STORE-002",
      "FR-STORE-003",
      "FR-NET-001",
      "FR-NET-002",
      "FR-NET-003"
    ],
    "since": 1
  },
  {
    "name": "fr:library:importFolder",
    "domain": "library",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "批量导入目录下的 PDF（递归可选，逐文件容错，单文件失败不中断整批）",
    "request": {
      "$ref": "#/$defs/LibraryImportFolderRequest"
    },
    "response": {
      "$ref": "#/$defs/LibraryImportFolderResponse"
    },
    "errors": [
      "FR-STORE-002"
    ],
    "since": 1
  },
  {
    "name": "fr:library:remove",
    "domain": "library",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "从库中移除条目；deleteFiles=true 时移入 .trash 并联动清理索引与缓存",
    "request": {
      "$ref": "#/$defs/LibraryRemoveRequest"
    },
    "response": {
      "$ref": "#/$defs/LibraryRemoveResponse"
    },
    "errors": [
      "FR-LIB-009",
      "FR-STORE-002"
    ],
    "since": 1
  },
  {
    "name": "fr:library:rename",
    "domain": "library",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "修改 citekey（原子重命名知识库目录；被其他 docId 占用则拒绝）",
    "request": {
      "$ref": "#/$defs/LibraryRenameRequest"
    },
    "response": {
      "$ref": "#/$defs/LibraryRenameResponse"
    },
    "errors": [
      "FR-LIB-005",
      "FR-LIB-007",
      "FR-LIB-009",
      "FR-STORE-002",
      "FR-STORE-003"
    ],
    "since": 1
  },
  {
    "name": "fr:library:updateMeta",
    "domain": "library",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "部分更新 meta.json（docId/citekey/addedAt/updatedAt/source 不可修改）",
    "request": {
      "$ref": "#/$defs/LibraryUpdateMetaRequest"
    },
    "response": {
      "$ref": "#/$defs/LibraryUpdateMetaResponse"
    },
    "errors": [
      "FR-LIB-005",
      "FR-LIB-009",
      "FR-STORE-002"
    ],
    "since": 1
  },
  {
    "name": "fr:library:reindex",
    "domain": "library",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "重建 SQLite 索引与 FTS5（文件为真源，索引可丢弃重建）",
    "request": {
      "$ref": "#/$defs/LibraryReindexRequest"
    },
    "response": {
      "$ref": "#/$defs/LibraryReindexResponse"
    },
    "errors": [
      "FR-STORE-002",
      "FR-STORE-004"
    ],
    "since": 1
  },
  {
    "name": "fr:library:listTags",
    "domain": "library",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "列出全部标签及其引用计数",
    "request": {
      "$ref": "#/$defs/LibraryListTagsRequest"
    },
    "response": {
      "$ref": "#/$defs/LibraryListTagsResponse"
    },
    "errors": [],
    "since": 1
  },
  {
    "name": "fr:library:setTags",
    "domain": "library",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "按 replace/add/remove 三种模式修改单个文档的标签",
    "request": {
      "$ref": "#/$defs/LibrarySetTagsRequest"
    },
    "response": {
      "$ref": "#/$defs/LibrarySetTagsResponse"
    },
    "errors": [
      "FR-LIB-005",
      "FR-LIB-009"
    ],
    "since": 1
  },
  {
    "name": "fr:doc:open",
    "domain": "doc",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "打开阅读会话（docId 或 citekey 恰好一个），返回会话 id、pdfUrl 与上次阅读位置",
    "request": {
      "$ref": "#/$defs/DocOpenRequest"
    },
    "response": {
      "$ref": "#/$defs/DocOpenResponse"
    },
    "errors": [
      "FR-LIB-005",
      "FR-ANCHOR-009"
    ],
    "since": 1
  },
  {
    "name": "fr:doc:close",
    "domain": "doc",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "关闭阅读会话；closing 阶段同步写入 ReadingProgress（位置永不丢失）",
    "request": {
      "$ref": "#/$defs/DocCloseRequest"
    },
    "response": {
      "$ref": "#/$defs/DocCloseResponse"
    },
    "errors": [],
    "since": 1
  },
  {
    "name": "fr:doc:getAnchorModel",
    "domain": "doc",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "取整篇 DocAnchorModel（blocks.json）；未解析返回 FR-LIB-005，绝不现场解析",
    "request": {
      "$ref": "#/$defs/DocGetAnchorModelRequest"
    },
    "response": {
      "$ref": "#/$defs/DocGetAnchorModelResponse"
    },
    "errors": [
      "FR-LIB-005",
      "FR-ANCHOR-009"
    ],
    "since": 1
  },
  {
    "name": "fr:doc:getPageBitmap",
    "domain": "doc",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "取某页背景位图（默认 110 dpi / WebP），经 fr-cache:// 协议或 base64 传输",
    "request": {
      "$ref": "#/$defs/DocGetPageBitmapRequest"
    },
    "response": {
      "$ref": "#/$defs/DocGetPageBitmapResponse"
    },
    "errors": [
      "FR-LIB-005"
    ],
    "since": 1
  },
  {
    "name": "fr:doc:exportPatch",
    "domain": "doc",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "把本地纠错补丁导出为标准化 JSON（含引擎版本与页面指纹），可社区汇总",
    "request": {
      "$ref": "#/$defs/DocExportPatchRequest"
    },
    "response": {
      "$ref": "#/$defs/DocExportPatchResponse"
    },
    "errors": [
      "FR-LIB-005",
      "FR-ANCHOR-012"
    ],
    "since": 1
  },
  {
    "name": "fr:doc:applyPatch",
    "domain": "doc",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "应用纠错补丁并立即重渲染（不重跑模型）；原子替换，失败整体回滚",
    "request": {
      "$ref": "#/$defs/DocApplyPatchRequest"
    },
    "response": {
      "$ref": "#/$defs/DocApplyPatchResponse"
    },
    "errors": [
      "FR-ANCHOR-010",
      "FR-ANCHOR-012"
    ],
    "since": 1
  },
  {
    "name": "fr:doc:search",
    "domain": "doc",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "FTS5 检索（库级或单文档级），返回句子级命中与定位锚点",
    "request": {
      "$ref": "#/$defs/DocSearchRequest"
    },
    "response": {
      "$ref": "#/$defs/DocSearchResponse"
    },
    "errors": [
      "FR-LIB-005"
    ],
    "since": 1
  },
  {
    "name": "fr:parser:start",
    "domain": "parser",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "提交解析作业；同 cacheKey 幂等（命中缓存或已有在跑任务时复用 jobId）",
    "request": {
      "$ref": "#/$defs/ParserStartRequest"
    },
    "response": {
      "$ref": "#/$defs/ParserStartResponse"
    },
    "errors": [
      "FR-LIB-001",
      "FR-LIB-002",
      "FR-LIB-005",
      "FR-PARSE-003",
      "FR-PARSE-004",
      "FR-PARSE-008",
      "FR-PARSE-010",
      "FR-PARSE-012"
    ],
    "since": 1
  },
  {
    "name": "fr:parser:cancel",
    "domain": "parser",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "取消解析作业；对 failed/canceled 幂等返回 canceled:false，终态不可取消",
    "request": {
      "$ref": "#/$defs/ParserCancelRequest"
    },
    "response": {
      "$ref": "#/$defs/ParserCancelResponse"
    },
    "errors": [],
    "since": 1
  },
  {
    "name": "fr:parser:health",
    "domain": "parser",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "sidecar 健康检查（单次超时 BUDGETS.SIDECAR_HEALTH_MS；失败不抛错，返回 ok:false）",
    "request": {
      "$ref": "#/$defs/ParserHealthRequest"
    },
    "response": {
      "$ref": "#/$defs/ParserHealthResponse"
    },
    "errors": [],
    "since": 1
  },
  {
    "name": "fr:parser:listEngines",
    "domain": "parser",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "列出引擎、模型与 OCR 的可用性（含体积、许可、present），供设置页与降级决策",
    "request": {
      "$ref": "#/$defs/ParserListEnginesRequest"
    },
    "response": {
      "$ref": "#/$defs/ParserListEnginesResponse"
    },
    "errors": [],
    "since": 1
  },
  {
    "name": "fr:parser:consentModelDownload",
    "domain": "parser",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "记录用户对模型下载的同意/拒绝并触发主进程经 NetGuard 下载（sidecar 绝不下载）",
    "request": {
      "$ref": "#/$defs/ParserConsentModelDownloadRequest"
    },
    "response": {
      "$ref": "#/$defs/ParserConsentModelDownloadResponse"
    },
    "errors": [
      "FR-NET-003",
      "FR-STORE-001",
      "FR-STORE-002"
    ],
    "since": 1
  },
  {
    "name": "fr:notes:list",
    "domain": "notes",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "分页列出某文档的标注/笔记（真源 annotations.jsonl；墓碑默认不返回）",
    "request": {
      "$ref": "#/$defs/NotesListRequest"
    },
    "response": {
      "$ref": "#/$defs/NotesListResponse"
    },
    "errors": [
      "FR-LIB-005",
      "FR-NOTE-001"
    ],
    "since": 1
  },
  {
    "name": "fr:notes:upsert",
    "domain": "notes",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "按 id 幂等写入一条标注（id 由 renderer 用 ULID 生成）；锚点失效时标 orphan 而非丢弃",
    "request": {
      "$ref": "#/$defs/NotesUpsertRequest"
    },
    "response": {
      "$ref": "#/$defs/NotesUpsertResponse"
    },
    "errors": [
      "FR-LIB-005",
      "FR-NOTE-001",
      "FR-NOTE-003",
      "FR-NOTE-004",
      "FR-STORE-002"
    ],
    "since": 1
  },
  {
    "name": "fr:notes:delete",
    "domain": "notes",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "删除标注（默认追加 deleted:true 墓碑，禁止物理删除行；hard=true 仅测试用）",
    "request": {
      "$ref": "#/$defs/NotesDeleteRequest"
    },
    "response": {
      "$ref": "#/$defs/NotesDeleteResponse"
    },
    "errors": [
      "FR-LIB-005",
      "FR-NOTE-001",
      "FR-NOTE-005"
    ],
    "since": 1
  },
  {
    "name": "fr:notes:exportMarkdown",
    "domain": "notes",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "导出笔记+标注为 Markdown；落盘位置只由主进程的保存对话框决定，回传文件名而非绝对路径",
    "request": {
      "$ref": "#/$defs/NotesExportMarkdownRequest"
    },
    "response": {
      "$ref": "#/$defs/NotesExportMarkdownResponse"
    },
    "errors": [
      "FR-LIB-005",
      "FR-NOTE-001",
      "FR-STORE-001",
      "FR-STORE-002"
    ],
    "since": 1
  },
  {
    "name": "fr:notes:importMarkdown",
    "domain": "notes",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "从 Markdown 导入标注（front-matter 必须含 docId 与锚点）；merge 优先，冲突保留本地",
    "request": {
      "$ref": "#/$defs/NotesImportMarkdownRequest"
    },
    "response": {
      "$ref": "#/$defs/NotesImportMarkdownResponse"
    },
    "errors": [
      "FR-LIB-005",
      "FR-NOTE-001",
      "FR-NOTE-003"
    ],
    "since": 1
  },
  {
    "name": "fr:notes:updateProgress",
    "domain": "notes",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "写入阅读位置（句子锚点 + 模式 + 滚动比例），clientEventId 幂等；供跨模式与崩溃恢复",
    "request": {
      "$ref": "#/$defs/NotesUpdateProgressRequest"
    },
    "response": {
      "$ref": "#/$defs/NotesUpdateProgressResponse"
    },
    "errors": [
      "FR-LIB-005",
      "FR-NOTE-003",
      "FR-STORE-002"
    ],
    "since": 1
  },
  {
    "name": "fr:translate:translateUnits",
    "domain": "translate",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "批量翻译：document 分支按 unitIds 由主进程解析原文，selection 分支翻译划词文本",
    "request": {
      "$ref": "#/$defs/TranslateUnitsRequest"
    },
    "response": {
      "$ref": "#/$defs/TranslateUnitsResponse"
    },
    "errors": [
      "FR-LIB-005",
      "FR-TRANS-001",
      "FR-TRANS-002",
      "FR-TRANS-003",
      "FR-TRANS-004",
      "FR-TRANS-005",
      "FR-TRANS-006",
      "FR-TRANS-007",
      "FR-TRANS-008",
      "FR-TRANS-009",
      "FR-TRANS-010",
      "FR-TRANS-011",
      "FR-TRANS-012",
      "FR-TRANS-013",
      "FR-TRANS-015",
      "FR-TRANS-016",
      "FR-TRANS-017",
      "FR-NET-003"
    ],
    "since": 1
  },
  {
    "name": "fr:translate:cancel",
    "domain": "translate",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "按 requestId 取消进行中的翻译（AbortSignal 透传到 Provider）；已结束则 canceled:false",
    "request": {
      "$ref": "#/$defs/TranslateCancelRequest"
    },
    "response": {
      "$ref": "#/$defs/TranslateCancelResponse"
    },
    "errors": [],
    "since": 1
  },
  {
    "name": "fr:translate:getCache",
    "domain": "translate",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "读取段落/句子级译文缓存（真源 translation/<lang>.jsonl，可由索引加速）",
    "request": {
      "$ref": "#/$defs/TranslateGetCacheRequest"
    },
    "response": {
      "$ref": "#/$defs/TranslateGetCacheResponse"
    },
    "errors": [
      "FR-LIB-005",
      "FR-TRANS-015",
      "FR-STORE-004"
    ],
    "since": 1
  },
  {
    "name": "fr:translate:clearCache",
    "domain": "translate",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "清理译文缓存（可按文档/语言/年龄过滤）；绝不影响 paper.pdf/blocks.json/笔记",
    "request": {
      "$ref": "#/$defs/TranslateClearCacheRequest"
    },
    "response": {
      "$ref": "#/$defs/TranslateClearCacheResponse"
    },
    "errors": [
      "FR-STORE-002",
      "FR-STORE-007"
    ],
    "since": 1
  },
  {
    "name": "fr:translate:listProviders",
    "domain": "translate",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "列出 Provider 与能力/可用状态；只回 host，绝不回密钥",
    "request": {
      "$ref": "#/$defs/TranslateListProvidersRequest"
    },
    "response": {
      "$ref": "#/$defs/TranslateListProvidersResponse"
    },
    "errors": [],
    "since": 1
  },
  {
    "name": "fr:translate:testProvider",
    "domain": "translate",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "连通性探测（固定短句，不发送文档内容）",
    "request": {
      "$ref": "#/$defs/TranslateTestProviderRequest"
    },
    "response": {
      "$ref": "#/$defs/TranslateTestProviderResponse"
    },
    "errors": [
      "FR-TRANS-001",
      "FR-TRANS-002",
      "FR-TRANS-004",
      "FR-TRANS-010",
      "FR-NET-002",
      "FR-NET-003"
    ],
    "since": 1
  },
  {
    "name": "fr:translate:listGlossary",
    "domain": "translate",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "列出术语表条目（scope 决定读 library/<citekey>/glossary.csv 还是共享表）",
    "request": {
      "$ref": "#/$defs/TranslateListGlossaryRequest"
    },
    "response": {
      "$ref": "#/$defs/TranslateListGlossaryResponse"
    },
    "errors": [
      "FR-LIB-005"
    ],
    "since": 1
  },
  {
    "name": "fr:translate:upsertGlossary",
    "domain": "translate",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "批量新增/更新术语（去重键 = caseSensitive ? source : source.toLocaleLowerCase('en-US')）",
    "request": {
      "$ref": "#/$defs/TranslateUpsertGlossaryRequest"
    },
    "response": {
      "$ref": "#/$defs/TranslateUpsertGlossaryResponse"
    },
    "errors": [
      "FR-LIB-005",
      "FR-TRANS-007",
      "FR-TRANS-014",
      "FR-STORE-002"
    ],
    "since": 1
  },
  {
    "name": "fr:translate:deleteGlossary",
    "domain": "translate",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "按 source 批量删除术语",
    "request": {
      "$ref": "#/$defs/TranslateDeleteGlossaryRequest"
    },
    "response": {
      "$ref": "#/$defs/TranslateDeleteGlossaryResponse"
    },
    "errors": [
      "FR-LIB-005",
      "FR-STORE-002"
    ],
    "since": 1
  },
  {
    "name": "fr:fetch:resolveMetadata",
    "domain": "fetch",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "按 DOI 解析元数据（Crossref/OpenAlex，经 NetGuard；失败只补全不覆盖已有值）",
    "request": {
      "$ref": "#/$defs/FetchResolveMetadataRequest"
    },
    "response": {
      "$ref": "#/$defs/FetchResolveMetadataResponse"
    },
    "errors": [
      "FR-FETCH-002",
      "FR-FETCH-003",
      "FR-FETCH-004",
      "FR-NET-001",
      "FR-NET-002",
      "FR-NET-003"
    ],
    "since": 1
  },
  {
    "name": "fr:fetch:fetchOpenAccess",
    "domain": "fetch",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "按 OA 白名单来源尝试获取全文；无 OA 时返回 needs-user-session，绝不回退任何绕过渠道",
    "request": {
      "$ref": "#/$defs/FetchOpenAccessRequest"
    },
    "response": {
      "$ref": "#/$defs/FetchOpenAccessResponse"
    },
    "errors": [
      "FR-LIB-001",
      "FR-LIB-002",
      "FR-LIB-005",
      "FR-FETCH-001",
      "FR-FETCH-002",
      "FR-NET-001",
      "FR-NET-002",
      "FR-NET-003"
    ],
    "since": 1
  },
  {
    "name": "fr:fetch:listProviders",
    "domain": "fetch",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "列出 FetchProvider 的域名、启用状态与凭据要求（决定是否弹用户会话提示）",
    "request": {
      "$ref": "#/$defs/FetchListProvidersRequest"
    },
    "response": {
      "$ref": "#/$defs/FetchListProvidersResponse"
    },
    "errors": [],
    "since": 1
  },
  {
    "name": "fr:fetch:auditLog",
    "domain": "fetch",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "查询 NetGuard 出站审计日志（字段与 09-fetch-compliance.md §6 的 net-audit.jsonl 一致；本地可查，默认不上传）",
    "request": {
      "$ref": "#/$defs/FetchAuditLogRequest"
    },
    "response": {
      "$ref": "#/$defs/FetchAuditLogResponse"
    },
    "errors": [],
    "since": 1
  },
  {
    "name": "fr:zotero:detect",
    "domain": "zotero",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "探测本机 Zotero 数据目录与版本；找不到不是错误，返回 found:false",
    "request": {
      "$ref": "#/$defs/ZoteroDetectRequest"
    },
    "response": {
      "$ref": "#/$defs/ZoteroDetectResponse"
    },
    "errors": [],
    "since": 1
  },
  {
    "name": "fr:zotero:listCollections",
    "domain": "zotero",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "列出 Zotero 分类及条目数（基于只读副本，不锁用户库）",
    "request": {
      "$ref": "#/$defs/ZoteroListCollectionsRequest"
    },
    "response": {
      "$ref": "#/$defs/ZoteroListCollectionsResponse"
    },
    "errors": [
      "FR-LIB-005",
      "FR-LIB-009",
      "FR-STORE-002",
      "FR-STORE-004"
    ],
    "since": 1
  },
  {
    "name": "fr:zotero:importSelection",
    "domain": "zotero",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "只读导入选中分类/条目到本地文献库；逐条目容错（单条问题进 failures[]），V1 绝不写用户 Zotero 库",
    "request": {
      "$ref": "#/$defs/ZoteroImportSelectionRequest"
    },
    "response": {
      "$ref": "#/$defs/ZoteroImportSelectionResponse"
    },
    "errors": [
      "FR-LIB-005",
      "FR-LIB-009",
      "FR-STORE-002"
    ],
    "since": 1
  },
  {
    "name": "fr:zotero:status",
    "domain": "zotero",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "查询上一次/进行中的 Zotero 导入状态",
    "request": {
      "$ref": "#/$defs/ZoteroStatusRequest"
    },
    "response": {
      "$ref": "#/$defs/ZoteroStatusResponse"
    },
    "errors": [],
    "since": 1
  },
  {
    "name": "fr:app:getConfig",
    "domain": "app",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "读取 config.json（含 revision 供乐观并发）；损坏时返回默认值 + FR-STORE-008",
    "request": {
      "$ref": "#/$defs/AppGetConfigRequest"
    },
    "response": {
      "$ref": "#/$defs/AppGetConfigResponse"
    },
    "errors": [],
    "since": 1
  },
  {
    "name": "fr:app:setConfig",
    "domain": "app",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "部分更新配置；未知 key 由 zod 拒绝，越界取值返回 FR-STORE-008",
    "request": {
      "$ref": "#/$defs/AppSetConfigRequest"
    },
    "response": {
      "$ref": "#/$defs/AppSetConfigResponse"
    },
    "errors": [
      "FR-STORE-002",
      "FR-STORE-008"
    ],
    "since": 1
  },
  {
    "name": "fr:app:getVersion",
    "domain": "app",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "返回应用与运行时版本（用于问题报告与 /doctor 头信息）",
    "request": {
      "$ref": "#/$defs/AppGetVersionRequest"
    },
    "response": {
      "$ref": "#/$defs/AppGetVersionResponse"
    },
    "errors": [],
    "since": 1
  },
  {
    "name": "fr:app:checkUpdate",
    "domain": "app",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "主动检查更新（仅签名包；更新源可配置）；失败静默降级为状态 error",
    "request": {
      "$ref": "#/$defs/AppCheckUpdateRequest"
    },
    "response": {
      "$ref": "#/$defs/AppCheckUpdateResponse"
    },
    "errors": [
      "FR-NET-001",
      "FR-NET-002",
      "FR-NET-005"
    ],
    "since": 1
  },
  {
    "name": "fr:app:openExternal",
    "domain": "app",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "用系统浏览器打开外链；必须经 NetGuard 校验（仅 https，白名单或用户显式确认）并写审计",
    "request": {
      "$ref": "#/$defs/AppOpenExternalRequest"
    },
    "response": {
      "$ref": "#/$defs/AppOpenExternalResponse"
    },
    "errors": [
      "FR-NET-001",
      "FR-NET-002",
      "FR-NET-003"
    ],
    "since": 1
  },
  {
    "name": "fr:app:exportLogs",
    "domain": "app",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "导出脱敏日志包（Redactor 强制）；落盘位置只由保存对话框决定，回传文件名",
    "request": {
      "$ref": "#/$defs/AppExportLogsRequest"
    },
    "response": {
      "$ref": "#/$defs/AppExportLogsResponse"
    },
    "errors": [
      "FR-STORE-001",
      "FR-STORE-002"
    ],
    "since": 1
  },
  {
    "name": "fr:app:getCacheInfo",
    "domain": "app",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "统计各类缓存占用（页面位图/译文/OCR/模型/日志）与上限",
    "request": {
      "$ref": "#/$defs/AppGetCacheInfoRequest"
    },
    "response": {
      "$ref": "#/$defs/AppGetCacheInfoResponse"
    },
    "errors": [
      "FR-STORE-007"
    ],
    "since": 1
  },
  {
    "name": "fr:app:clearCache",
    "domain": "app",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "清理指定类别缓存（可重建）；位图/译文缺失只会重生成，不影响真源",
    "request": {
      "$ref": "#/$defs/AppClearCacheRequest"
    },
    "response": {
      "$ref": "#/$defs/AppClearCacheResponse"
    },
    "errors": [
      "FR-STORE-002",
      "FR-STORE-007"
    ],
    "since": 1
  },
  {
    "name": "fr:app:doctor",
    "domain": "app",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "应用内自检/修复（等价 freeread doctor 子命令）；问题以 checks[] 逐项报告，不抛错",
    "request": {
      "$ref": "#/$defs/AppDoctorRequest"
    },
    "response": {
      "$ref": "#/$defs/AppDoctorResponse"
    },
    "errors": [
      "FR-STORE-002",
      "FR-STORE-004"
    ],
    "since": 1
  },
  {
    "name": "fr:app:getCapabilities",
    "domain": "app",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "能力协商：UI 据此降级；quickMode 恒等于 (engine === 'rule')，驱动快速模式横幅",
    "request": {
      "$ref": "#/$defs/AppGetCapabilitiesRequest"
    },
    "response": {
      "$ref": "#/$defs/AppGetCapabilitiesResponse"
    },
    "errors": [],
    "since": 1
  },
  {
    "name": "fr:app:getApiVersion",
    "domain": "app",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "渲染端启动握手：返回 apiVersion 与通道/事件级 since 表及废弃列表",
    "request": {
      "$ref": "#/$defs/AppGetApiVersionRequest"
    },
    "response": {
      "$ref": "#/$defs/AppGetApiVersionResponse"
    },
    "errors": [],
    "since": 1
  },
  {
    "name": "fr:window:openReaderTab",
    "domain": "window",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "打开阅读器文档视图（V1：每个 BrowserWindow 仅 1 个视图；多视图为 V2）",
    "request": {
      "$ref": "#/$defs/WindowOpenReaderTabRequest"
    },
    "response": {
      "$ref": "#/$defs/WindowOpenReaderTabResponse"
    },
    "errors": [
      "FR-LIB-005"
    ],
    "since": 1
  },
  {
    "name": "fr:window:closeTab",
    "domain": "window",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "关闭文档视图并释放其阅读会话（先同步落盘阅读位置）",
    "request": {
      "$ref": "#/$defs/WindowCloseTabRequest"
    },
    "response": {
      "$ref": "#/$defs/WindowCloseTabResponse"
    },
    "errors": [],
    "since": 1
  },
  {
    "name": "fr:window:focusMain",
    "domain": "window",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "聚焦主窗口（托盘/通知/外链返回后回到前台）",
    "request": {
      "$ref": "#/$defs/WindowFocusMainRequest"
    },
    "response": {
      "$ref": "#/$defs/WindowFocusMainResponse"
    },
    "errors": [],
    "since": 1
  },
  {
    "name": "fr:agent:start",
    "domain": "agent",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "创建 Agent 会话（可指定 projectId/title）；未配置 LLM Provider **不失败**：返回 llmReady:false 并置空 activeProviderId，由 UI 显示配置引导（14-agent.md §10.2）",
    "request": {
      "$ref": "#/$defs/AgentStartRequest"
    },
    "response": {
      "$ref": "#/$defs/AgentStartResponse"
    },
    "errors": [
      "FR-AGT-012",
      "FR-STORE-002",
      "FR-STORE-012"
    ],
    "since": 1
  },
  {
    "name": "fr:agent:send",
    "domain": "agent",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "发送用户消息并启动一个 run（返回 runId）；未配置可用 Provider → ok:false + FR-AGT-001（warn 级但操作无法完成）；run 开始后的失败全部经 fr:agent:event 回推；附件只允许文献库 docId 或工作区相对路径",
    "request": {
      "$ref": "#/$defs/AgentSendRequest"
    },
    "response": {
      "$ref": "#/$defs/AgentSendResponse"
    },
    "errors": [
      "FR-AGT-001",
      "FR-AGT-012",
      "FR-STORE-002"
    ],
    "since": 1
  },
  {
    "name": "fr:agent:cancel",
    "domain": "agent",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "取消会话当前活动 run（已终态则 canceled:false，幂等非错误）；已产出内容保留（14-agent.md §3.1）",
    "request": {
      "$ref": "#/$defs/AgentCancelRequest"
    },
    "response": {
      "$ref": "#/$defs/AgentCancelResponse"
    },
    "errors": [],
    "since": 1
  },
  {
    "name": "fr:agent:listSessions",
    "domain": "agent",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "按 projectId 分页列出会话摘要（强制分页；摘要不含笔记/译文全文，AG-8）",
    "request": {
      "$ref": "#/$defs/AgentListSessionsRequest"
    },
    "response": {
      "$ref": "#/$defs/AgentListSessionsResponse"
    },
    "errors": [],
    "since": 1
  },
  {
    "name": "fr:agent:getSession",
    "domain": "agent",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "取会话元信息 + 事件流（afterSeq 增量，事件行逐条过 agent-session.schema.json）；损坏行跳过并计 unparsableLines（FR-AGT-010，绝不整体失败）；事件流是回放真源，事件通知不是",
    "request": {
      "$ref": "#/$defs/AgentGetSessionRequest"
    },
    "response": {
      "$ref": "#/$defs/AgentGetSessionResponse"
    },
    "errors": [
      "FR-AGT-010",
      "FR-STORE-002"
    ],
    "since": 1
  },
  {
    "name": "fr:agent:deleteSession",
    "domain": "agent",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "删除会话文件与事件流（立即生效，不写墓碑）；审计行按 11-error-handling.md §3 保留策略留存",
    "request": {
      "$ref": "#/$defs/AgentDeleteSessionRequest"
    },
    "response": {
      "$ref": "#/$defs/AgentDeleteSessionResponse"
    },
    "errors": [
      "FR-STORE-002",
      "FR-STORE-012"
    ],
    "since": 1
  },
  {
    "name": "fr:agent:listTools",
    "domain": "agent",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "列出工具清单（V1 恒 14 个，含 inputSchema/sideEffect/defaultRule）+ 项目权限表 + Provider 能力；UI 据此渲染权限面板",
    "request": {
      "$ref": "#/$defs/AgentListToolsRequest"
    },
    "response": {
      "$ref": "#/$defs/AgentListToolsResponse"
    },
    "errors": [
      "FR-AGT-012"
    ],
    "since": 1
  },
  {
    "name": "fr:agent:setPermissionRule",
    "domain": "agent",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "设置某工具的权限规则并落盘 permissions.json（deny 为项目内终态，只能由本通道显式改回；必写审计）",
    "request": {
      "$ref": "#/$defs/AgentSetPermissionRuleRequest"
    },
    "response": {
      "$ref": "#/$defs/AgentSetPermissionRuleResponse"
    },
    "errors": [
      "FR-AGT-012",
      "FR-STORE-002",
      "FR-STORE-012"
    ],
    "since": 1
  },
  {
    "name": "fr:agent:listSkills",
    "domain": "agent",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "列出项目已安装技能（含 valid/reason）；无效技能不注入上下文",
    "request": {
      "$ref": "#/$defs/AgentListSkillsRequest"
    },
    "response": {
      "$ref": "#/$defs/AgentListSkillsResponse"
    },
    "errors": [
      "FR-AGT-012"
    ],
    "since": 1
  },
  {
    "name": "fr:agent:installSkill",
    "domain": "agent",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "从本地目录安装技能（V1 禁止远端下载）：校验 SKILL.md front-matter、许可清单、路径穿越、文件数 ≤ 200 与总体积 ≤ 20 MiB，失败一律 FR-AGT-009",
    "request": {
      "$ref": "#/$defs/AgentInstallSkillRequest"
    },
    "response": {
      "$ref": "#/$defs/AgentInstallSkillResponse"
    },
    "errors": [
      "FR-AGT-009",
      "FR-AGT-012",
      "FR-STORE-001",
      "FR-STORE-002"
    ],
    "since": 1
  },
  {
    "name": "fr:project:ensure",
    "domain": "project",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "创建或打开项目（projectId 与 title 恰好一个），由主进程建立 project.json/permissions.json/skills/workspace/sessions 目录树；renderer 永不传路径",
    "request": {
      "$ref": "#/$defs/ProjectEnsureRequest"
    },
    "response": {
      "$ref": "#/$defs/ProjectEnsureResponse"
    },
    "errors": [
      "FR-AGT-012",
      "FR-STORE-001",
      "FR-STORE-002"
    ],
    "since": 1
  },
  {
    "name": "fr:project:getPermissions",
    "domain": "project",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "读取项目权限表 permissions.json（不合 schema 时用各工具 defaultRule 重建并置 restoredFromDefaults:true）",
    "request": {
      "$ref": "#/$defs/ProjectGetPermissionsRequest"
    },
    "response": {
      "$ref": "#/$defs/ProjectGetPermissionsResponse"
    },
    "errors": [
      "FR-AGT-012",
      "FR-STORE-002"
    ],
    "since": 1
  },
  {
    "name": "fr:project:listFiles",
    "domain": "project",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "分页列出工作区文件（只回工作区相对路径，禁止绝对路径）；dir 经 assertWorkspaceRelPath + assertContainedPath 双重校验",
    "request": {
      "$ref": "#/$defs/ProjectListFilesRequest"
    },
    "response": {
      "$ref": "#/$defs/ProjectListFilesResponse"
    },
    "errors": [
      "FR-AGT-012"
    ],
    "since": 1
  },
  {
    "name": "fr:project:importFiles",
    "domain": "project",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "把用户选择（系统对话框/拖放）的本地文件导入工作区：逐文件容错（单文件问题进 failures[]），回传相对路径而非绝对路径",
    "request": {
      "$ref": "#/$defs/ProjectImportFilesRequest"
    },
    "response": {
      "$ref": "#/$defs/ProjectImportFilesResponse"
    },
    "errors": [
      "FR-AGT-012",
      "FR-STORE-001",
      "FR-STORE-002"
    ],
    "since": 1
  },
  {
    "name": "fr:project:exportZip",
    "domain": "project",
    "kind": "invoke",
    "direction": "renderer->main",
    "summary": "导出项目 zip（project.json + workspace/ + skills/；恒不含 permissions.json 与 sessions/）：落盘位置只由系统保存对话框决定，回文件名",
    "request": {
      "$ref": "#/$defs/ProjectExportZipRequest"
    },
    "response": {
      "$ref": "#/$defs/ProjectExportZipResponse"
    },
    "errors": [
      "FR-AGT-012",
      "FR-STORE-001",
      "FR-STORE-002"
    ],
    "since": 1
  }
] as const;
