// Generated by pnpm gen. Do not edit.

/**
 * This interface was referenced by `DocAnchorModel`'s JSON-Schema
 * via the `definition` "PageNo".
 */
export type PageNo = number;
/**
 * This interface was referenced by `DocAnchorModel`'s JSON-Schema
 * via the `definition` "BlockType".
 */
export type BlockType =
  | 'title'
  | 'author'
  | 'abstract'
  | 'heading'
  | 'text'
  | 'figure'
  | 'figure_caption'
  | 'table'
  | 'table_caption'
  | 'formula'
  | 'inline_formula'
  | 'reference'
  | 'aside'
  | 'abandon';

/**
 * FreeRead 锚点模型（blocks.json）。权威定义，见 specs/03-anchor-model.md。修改必须 bump schemaVersion。
 */
export interface DocAnchorModel {
  schemaVersion: 1;
  /**
   * PDF 字节的 sha256（hex 小写）
   */
  docId: string;
  engine: {
    name: 'docling' | 'marker' | 'grobid' | 'rule';
    version: string;
  };
  /**
   * 可选的质量与形态标记（用于 UI 降级提示）
   */
  meta?: {
    quality?: 'native' | 'ocr' | 'mixed';
    writingMode?: 'horizontal-tb' | 'vertical-rl';
    pageCount?: number;
    parserRulesRevision?: number;
  };
  /**
   * 键为 1-based 页号的字符串；值为该页视觉方向尺寸（pt）
   */
  pageSize: {
    [k: string]: {
      w: number;
      h: number;
    };
  };
  blocks: Block[];
  paragraphs: Paragraph[];
  sentences: Sentence[];
  outline: OutlineItem[];
  figures: FigureRef[];
  references: ReferenceRef[];
  stats: Stats;
}
/**
 * This interface was referenced by `DocAnchorModel`'s JSON-Schema
 * via the `definition` "Block".
 */
export interface Block {
  id: string;
  page: PageNo;
  rect: Rect;
  type: BlockType;
  score: number;
  order: number;
  text?: string;
  lines?: LineRef[];
}
/**
 * This interface was referenced by `DocAnchorModel`'s JSON-Schema
 * via the `definition` "Rect".
 */
export interface Rect {
  x: number;
  y: number;
  w: number;
  h: number;
}
/**
 * This interface was referenced by `DocAnchorModel`'s JSON-Schema
 * via the `definition` "LineRef".
 */
export interface LineRef {
  lineId: number;
  page: PageNo;
  begin: number;
  len: number;
}
/**
 * This interface was referenced by `DocAnchorModel`'s JSON-Schema
 * via the `definition` "Paragraph".
 */
export interface Paragraph {
  id: string;
  /**
   * @minItems 1
   */
  blockIds: [string, ...string[]];
  sentenceIds: string[];
}
/**
 * This interface was referenced by `DocAnchorModel`'s JSON-Schema
 * via the `definition` "Sentence".
 */
export interface Sentence {
  id: string;
  blockId: string;
  page: PageNo;
  text: string;
  /**
   * @minItems 1
   */
  lines: [LineRef, ...LineRef[]];
  kind: 'text' | 'formula' | 'caption' | 'title' | 'reference';
}
/**
 * This interface was referenced by `DocAnchorModel`'s JSON-Schema
 * via the `definition` "OutlineItem".
 */
export interface OutlineItem {
  id: string;
  title: string;
  page: PageNo;
  blockId: string;
  level: number;
}
/**
 * This interface was referenced by `DocAnchorModel`'s JSON-Schema
 * via the `definition` "FigureRef".
 */
export interface FigureRef {
  id: string;
  tag: string;
  page: PageNo;
  blockId: string;
  caption?: string;
}
/**
 * This interface was referenced by `DocAnchorModel`'s JSON-Schema
 * via the `definition` "ReferenceRef".
 */
export interface ReferenceRef {
  id: string;
  tag: string;
  page: PageNo;
  text: string;
  doi?: string;
}
/**
 * This interface was referenced by `DocAnchorModel`'s JSON-Schema
 * via the `definition` "Stats".
 */
export interface Stats {
  blockCount: number;
  sentenceCount: number;
  lowConfidenceBlocks: number;
  durationMs: number;
}
