// Generated by pnpm gen. Do not edit.

/**
 * FreeRead 单条标注（library/<citekey>/annotations.jsonl 的一行）的权威契约。每行一个本对象、以 \n 结尾、只追加写、删除用 deleted:true 墓碑（specs/05-storage.md §4）。anchor 只允许引用 page/blockId/sentenceId/rects/lines；Rect 与 LineRef 的定义**复用** doc-anchor-model.schema.json，不得在本文件复制。修改字段语义必须 bump schemaVersion（specs/README.md F9）。
 */
export type Annotation = {
  /**
   * 标注格式版本；字段语义变更时必须 bump 并提供迁移（specs/05-storage.md §8）。
   */
  schemaVersion: 1;
  /**
   * 标注主键：'an_' + ULID（26 位 Crockford Base32，字典序即时间序）。同一 id 的多行中，文件中最后出现的一行为准。
   */
  id: string;
  /**
   * 文档指纹：paper.pdf 字节的 sha256（64 位小写 hex），必须等于同目录 meta.json#docId。
   */
  docId: string;
  /**
   * 标注类型；决定 anchor 与 note 的必填约束（见本文件顶部 allOf 分支）。
   */
  kind: 'highlight' | 'note' | 'bookmark' | 'ink';
  anchor?: Anchor;
  /**
   * 高亮/墨迹颜色；仅 kind ∈ {highlight, ink} 有意义（UI 侧映射为 --fr-* CSS 变量）。
   */
  color?: 'yellow' | 'green' | 'blue' | 'pink' | 'purple' | 'orange';
  /**
   * 用户笔记正文（纯文本或受限 Markdown，禁止 HTML）；kind='note' 时必填。
   */
  note?: string;
  /**
   * 被标注原文的快照（便于跨版本阅读与导出）；仅供展示，**不得**用它做定位——定位一律以 anchor.sentenceId 为准。
   */
  quote?: string;
  /**
   * 标注标签（扁平、≤ 32 字符/个），用于检索与筛选。
   *
   * @maxItems 32
   */
  tags?: string[];
  /**
   * 创建时刻，ISO 8601 UTC（如 '2026-10-03T00:31:12.480Z'）；一经写入不得修改。
   */
  createdAt: string;
  /**
   * 最后修改时刻，ISO 8601 UTC；必须 ≥ createdAt。修改标注 = 追加同 id 且带新 updatedAt 的一行。
   */
  updatedAt?: string;
  /**
   * 产生该标注的安装实例标识：'dev_' + ULID（安装时生成一次，存本机配置，不参与云同步冲突之外的用途）。
   */
  deviceId: string;
  /**
   * 墓碑标记。true 表示该 id 已被删除；**禁止物理删除 JSONL 行**，只有 freeread doctor --compact 才可压缩（specs/05-storage.md §9.1）。
   */
  deleted?: boolean;
  ink?: Ink;
};

/**
 * 锚点：定位到文档结构（sentenceId）与 PDF 几何（rects/lines）。highlight/note/ink 必填；bookmark 可省略（仅需 page/blockId）。
 */
export interface Anchor {
  /**
   * 1-based 页面号（PageNo），必须等于 sentenceId 所属句子的 page。
   */
  page: number;
  /**
   * 版面块 ID（camelCase 字段名遵循方案 §3.4 与 schemas 既有契约），必须存在于 blocks.json#blocks。
   */
  blockId: string;
  /**
   * 句子 ID，锚点系统的**唯一**定位依据（specs/03-anchor-model.md §4）；不存在时标为待重解析并报 FR-STORE-007，不得删除标注。
   */
  sentenceId: string;
  /**
   * 高亮几何（PDF point、页面左上原点、y 轴向下）。highlight/ink 必须非空；bookmark/note 允许为 [] 表示仅锚定句子、无几何框。
   *
   * @maxItems 256
   */
  rects: Rect[];
  /**
   * 覆盖的 PDF 文本层行区间；元素定义复用锚点模型，用于原文视图精确落框与调试。
   *
   * @maxItems 256
   */
  lines: LineRef[];
}
export interface Rect {
  x: number;
  y: number;
  w: number;
  h: number;
}
export interface LineRef {
  lineId: number;
  page: number;
  begin: number;
  len: number;
}
/**
 * 手写墨迹数据（仅 kind='ink' 使用）；矢量笔画存于本地附件文件，此处只存引用与包围盒。
 */
export interface Ink {
  /**
   * 相对 library/<citekey>/ 的笔画数据路径（禁止绝对路径）；如 'assets/ink/an_01H8ZQ.json'。
   */
  assetPath: string;
  bbox: Rect1;
  /**
   * 笔画数量（用于容量预算与渲染进度提示）。
   */
  strokeCount?: number;
}
/**
 * 墨迹在页面上的包围盒（PDF point），用于快速命中测试。
 */
export interface Rect1 {
  x: number;
  y: number;
  w: number;
  h: number;
}
/**
 * 跨模式锚点。只允许包含结构 ID 与 PDF pt 几何；禁止文本偏移、DOM 路径、像素坐标或缩放后坐标（specs/05-storage.md §4 A6/A7）。
 *
 * This interface was referenced by `undefined`'s JSON-Schema
 * via the `definition` "Anchor".
 */
export interface Anchor1 {
  /**
   * 1-based 页面号（PageNo），必须等于 sentenceId 所属句子的 page。
   */
  page: number;
  /**
   * 版面块 ID（camelCase 字段名遵循方案 §3.4 与 schemas 既有契约），必须存在于 blocks.json#blocks。
   */
  blockId: string;
  /**
   * 句子 ID，锚点系统的**唯一**定位依据（specs/03-anchor-model.md §4）；不存在时标为待重解析并报 FR-STORE-007，不得删除标注。
   */
  sentenceId: string;
  /**
   * 高亮几何（PDF point、页面左上原点、y 轴向下）。highlight/ink 必须非空；bookmark/note 允许为 [] 表示仅锚定句子、无几何框。
   *
   * @maxItems 256
   */
  rects: Rect[];
  /**
   * 覆盖的 PDF 文本层行区间；元素定义复用锚点模型，用于原文视图精确落框与调试。
   *
   * @maxItems 256
   */
  lines: LineRef[];
}
/**
 * 手写墨迹的引用（V1 仅存储与展示，不做识别）。
 *
 * This interface was referenced by `undefined`'s JSON-Schema
 * via the `definition` "Ink".
 */
export interface Ink1 {
  /**
   * 相对 library/<citekey>/ 的笔画数据路径（禁止绝对路径）；如 'assets/ink/an_01H8ZQ.json'。
   */
  assetPath: string;
  bbox: Rect1;
  /**
   * 笔画数量（用于容量预算与渲染进度提示）。
   */
  strokeCount?: number;
}
