// Generated by pnpm gen. Do not edit.
import type { IpcPayloads, FrEventName } from '@freeread/core';
export type ApiResult<T> = { ok: true; data: T } | { ok: false; error: IpcPayloads['ErrorObject'] };
export interface EventPayloads {
  'fr:parser:progress': IpcPayloads['ParseProgressEvent'];
  'fr:parser:failed': IpcPayloads['ParserFailedEvent'];
  'fr:translate:progress': IpcPayloads['TranslateProgressEvent'];
  'fr:library:changed': IpcPayloads['LibraryChangedEvent'];
  'fr:notes:changed': IpcPayloads['NotesChangedEvent'];
  'fr:app:updateAvailable': IpcPayloads['UpdateAvailableEvent'];
  'fr:agent:event': IpcPayloads['AgentEventPayload'];
  'fr:project:changed': IpcPayloads['ProjectChangedEvent'];
}
export type FrEvent<T extends FrEventName> = { type: T; payload: EventPayloads[T]; ts: number; seq: number };
export interface FrBridge {
  readonly local: { pickPdf(): Promise<string[]>; cancelImport(): Promise<void> };
  readonly library: {
    list(req: IpcPayloads['LibraryListRequest']): Promise<ApiResult<IpcPayloads['LibraryListResponse']>>;
    get(req: IpcPayloads['LibraryGetRequest']): Promise<ApiResult<IpcPayloads['LibraryGetResponse']>>;
    import(req: IpcPayloads['LibraryImportRequest']): Promise<ApiResult<IpcPayloads['LibraryImportResponse']>>;
    importFolder(req: IpcPayloads['LibraryImportFolderRequest']): Promise<ApiResult<IpcPayloads['LibraryImportFolderResponse']>>;
    remove(req: IpcPayloads['LibraryRemoveRequest']): Promise<ApiResult<IpcPayloads['LibraryRemoveResponse']>>;
    rename(req: IpcPayloads['LibraryRenameRequest']): Promise<ApiResult<IpcPayloads['LibraryRenameResponse']>>;
    updateMeta(req: IpcPayloads['LibraryUpdateMetaRequest']): Promise<ApiResult<IpcPayloads['LibraryUpdateMetaResponse']>>;
    reindex(req: IpcPayloads['LibraryReindexRequest']): Promise<ApiResult<IpcPayloads['LibraryReindexResponse']>>;
    listTags(req: IpcPayloads['LibraryListTagsRequest']): Promise<ApiResult<IpcPayloads['LibraryListTagsResponse']>>;
    setTags(req: IpcPayloads['LibrarySetTagsRequest']): Promise<ApiResult<IpcPayloads['LibrarySetTagsResponse']>>;
  };
  readonly doc: {
    open(req: IpcPayloads['DocOpenRequest']): Promise<ApiResult<IpcPayloads['DocOpenResponse']>>;
    close(req: IpcPayloads['DocCloseRequest']): Promise<ApiResult<IpcPayloads['DocCloseResponse']>>;
    getAnchorModel(req: IpcPayloads['DocGetAnchorModelRequest']): Promise<ApiResult<IpcPayloads['DocGetAnchorModelResponse']>>;
    getPageBitmap(req: IpcPayloads['DocGetPageBitmapRequest']): Promise<ApiResult<IpcPayloads['DocGetPageBitmapResponse']>>;
    exportPatch(req: IpcPayloads['DocExportPatchRequest']): Promise<ApiResult<IpcPayloads['DocExportPatchResponse']>>;
    applyPatch(req: IpcPayloads['DocApplyPatchRequest']): Promise<ApiResult<IpcPayloads['DocApplyPatchResponse']>>;
    search(req: IpcPayloads['DocSearchRequest']): Promise<ApiResult<IpcPayloads['DocSearchResponse']>>;
  };
  readonly parser: {
    start(req: IpcPayloads['ParserStartRequest']): Promise<ApiResult<IpcPayloads['ParserStartResponse']>>;
    cancel(req: IpcPayloads['ParserCancelRequest']): Promise<ApiResult<IpcPayloads['ParserCancelResponse']>>;
    health(req: IpcPayloads['ParserHealthRequest']): Promise<ApiResult<IpcPayloads['ParserHealthResponse']>>;
    listEngines(req: IpcPayloads['ParserListEnginesRequest']): Promise<ApiResult<IpcPayloads['ParserListEnginesResponse']>>;
    consentModelDownload(req: IpcPayloads['ParserConsentModelDownloadRequest']): Promise<ApiResult<IpcPayloads['ParserConsentModelDownloadResponse']>>;
  };
  readonly notes: {
    list(req: IpcPayloads['NotesListRequest']): Promise<ApiResult<IpcPayloads['NotesListResponse']>>;
    upsert(req: IpcPayloads['NotesUpsertRequest']): Promise<ApiResult<IpcPayloads['NotesUpsertResponse']>>;
    delete(req: IpcPayloads['NotesDeleteRequest']): Promise<ApiResult<IpcPayloads['NotesDeleteResponse']>>;
    exportMarkdown(req: IpcPayloads['NotesExportMarkdownRequest']): Promise<ApiResult<IpcPayloads['NotesExportMarkdownResponse']>>;
    importMarkdown(req: IpcPayloads['NotesImportMarkdownRequest']): Promise<ApiResult<IpcPayloads['NotesImportMarkdownResponse']>>;
    updateProgress(req: IpcPayloads['NotesUpdateProgressRequest']): Promise<ApiResult<IpcPayloads['NotesUpdateProgressResponse']>>;
  };
  readonly translate: {
    translateUnits(req: IpcPayloads['TranslateUnitsRequest']): Promise<ApiResult<IpcPayloads['TranslateUnitsResponse']>>;
    cancel(req: IpcPayloads['TranslateCancelRequest']): Promise<ApiResult<IpcPayloads['TranslateCancelResponse']>>;
    getCache(req: IpcPayloads['TranslateGetCacheRequest']): Promise<ApiResult<IpcPayloads['TranslateGetCacheResponse']>>;
    clearCache(req: IpcPayloads['TranslateClearCacheRequest']): Promise<ApiResult<IpcPayloads['TranslateClearCacheResponse']>>;
    listProviders(req: IpcPayloads['TranslateListProvidersRequest']): Promise<ApiResult<IpcPayloads['TranslateListProvidersResponse']>>;
    testProvider(req: IpcPayloads['TranslateTestProviderRequest']): Promise<ApiResult<IpcPayloads['TranslateTestProviderResponse']>>;
    listGlossary(req: IpcPayloads['TranslateListGlossaryRequest']): Promise<ApiResult<IpcPayloads['TranslateListGlossaryResponse']>>;
    upsertGlossary(req: IpcPayloads['TranslateUpsertGlossaryRequest']): Promise<ApiResult<IpcPayloads['TranslateUpsertGlossaryResponse']>>;
    deleteGlossary(req: IpcPayloads['TranslateDeleteGlossaryRequest']): Promise<ApiResult<IpcPayloads['TranslateDeleteGlossaryResponse']>>;
  };
  readonly fetch: {
    resolveMetadata(req: IpcPayloads['FetchResolveMetadataRequest']): Promise<ApiResult<IpcPayloads['FetchResolveMetadataResponse']>>;
    fetchOpenAccess(req: IpcPayloads['FetchOpenAccessRequest']): Promise<ApiResult<IpcPayloads['FetchOpenAccessResponse']>>;
    listProviders(req: IpcPayloads['FetchListProvidersRequest']): Promise<ApiResult<IpcPayloads['FetchListProvidersResponse']>>;
    auditLog(req: IpcPayloads['FetchAuditLogRequest']): Promise<ApiResult<IpcPayloads['FetchAuditLogResponse']>>;
  };
  readonly zotero: {
    detect(req: IpcPayloads['ZoteroDetectRequest']): Promise<ApiResult<IpcPayloads['ZoteroDetectResponse']>>;
    listCollections(req: IpcPayloads['ZoteroListCollectionsRequest']): Promise<ApiResult<IpcPayloads['ZoteroListCollectionsResponse']>>;
    importSelection(req: IpcPayloads['ZoteroImportSelectionRequest']): Promise<ApiResult<IpcPayloads['ZoteroImportSelectionResponse']>>;
    status(req: IpcPayloads['ZoteroStatusRequest']): Promise<ApiResult<IpcPayloads['ZoteroStatusResponse']>>;
  };
  readonly app: {
    getConfig(req: IpcPayloads['AppGetConfigRequest']): Promise<ApiResult<IpcPayloads['AppGetConfigResponse']>>;
    setConfig(req: IpcPayloads['AppSetConfigRequest']): Promise<ApiResult<IpcPayloads['AppSetConfigResponse']>>;
    getVersion(req: IpcPayloads['AppGetVersionRequest']): Promise<ApiResult<IpcPayloads['AppGetVersionResponse']>>;
    checkUpdate(req: IpcPayloads['AppCheckUpdateRequest']): Promise<ApiResult<IpcPayloads['AppCheckUpdateResponse']>>;
    openExternal(req: IpcPayloads['AppOpenExternalRequest']): Promise<ApiResult<IpcPayloads['AppOpenExternalResponse']>>;
    exportLogs(req: IpcPayloads['AppExportLogsRequest']): Promise<ApiResult<IpcPayloads['AppExportLogsResponse']>>;
    getCacheInfo(req: IpcPayloads['AppGetCacheInfoRequest']): Promise<ApiResult<IpcPayloads['AppGetCacheInfoResponse']>>;
    clearCache(req: IpcPayloads['AppClearCacheRequest']): Promise<ApiResult<IpcPayloads['AppClearCacheResponse']>>;
    doctor(req: IpcPayloads['AppDoctorRequest']): Promise<ApiResult<IpcPayloads['AppDoctorResponse']>>;
    getCapabilities(req: IpcPayloads['AppGetCapabilitiesRequest']): Promise<ApiResult<IpcPayloads['AppGetCapabilitiesResponse']>>;
    getApiVersion(req: IpcPayloads['AppGetApiVersionRequest']): Promise<ApiResult<IpcPayloads['AppGetApiVersionResponse']>>;
  };
  readonly window: {
    openReaderTab(req: IpcPayloads['WindowOpenReaderTabRequest']): Promise<ApiResult<IpcPayloads['WindowOpenReaderTabResponse']>>;
    closeTab(req: IpcPayloads['WindowCloseTabRequest']): Promise<ApiResult<IpcPayloads['WindowCloseTabResponse']>>;
    focusMain(req: IpcPayloads['WindowFocusMainRequest']): Promise<ApiResult<IpcPayloads['WindowFocusMainResponse']>>;
  };
  readonly agent: {
    start(req: IpcPayloads['AgentStartRequest']): Promise<ApiResult<IpcPayloads['AgentStartResponse']>>;
    send(req: IpcPayloads['AgentSendRequest']): Promise<ApiResult<IpcPayloads['AgentSendResponse']>>;
    cancel(req: IpcPayloads['AgentCancelRequest']): Promise<ApiResult<IpcPayloads['AgentCancelResponse']>>;
    listSessions(req: IpcPayloads['AgentListSessionsRequest']): Promise<ApiResult<IpcPayloads['AgentListSessionsResponse']>>;
    getSession(req: IpcPayloads['AgentGetSessionRequest']): Promise<ApiResult<IpcPayloads['AgentGetSessionResponse']>>;
    deleteSession(req: IpcPayloads['AgentDeleteSessionRequest']): Promise<ApiResult<IpcPayloads['AgentDeleteSessionResponse']>>;
    listTools(req: IpcPayloads['AgentListToolsRequest']): Promise<ApiResult<IpcPayloads['AgentListToolsResponse']>>;
    setPermissionRule(req: IpcPayloads['AgentSetPermissionRuleRequest']): Promise<ApiResult<IpcPayloads['AgentSetPermissionRuleResponse']>>;
    listSkills(req: IpcPayloads['AgentListSkillsRequest']): Promise<ApiResult<IpcPayloads['AgentListSkillsResponse']>>;
    installSkill(req: IpcPayloads['AgentInstallSkillRequest']): Promise<ApiResult<IpcPayloads['AgentInstallSkillResponse']>>;
  };
  readonly project: {
    ensure(req: IpcPayloads['ProjectEnsureRequest']): Promise<ApiResult<IpcPayloads['ProjectEnsureResponse']>>;
    getPermissions(req: IpcPayloads['ProjectGetPermissionsRequest']): Promise<ApiResult<IpcPayloads['ProjectGetPermissionsResponse']>>;
    listFiles(req: IpcPayloads['ProjectListFilesRequest']): Promise<ApiResult<IpcPayloads['ProjectListFilesResponse']>>;
    importFiles(req: IpcPayloads['ProjectImportFilesRequest']): Promise<ApiResult<IpcPayloads['ProjectImportFilesResponse']>>;
    exportZip(req: IpcPayloads['ProjectExportZipRequest']): Promise<ApiResult<IpcPayloads['ProjectExportZipResponse']>>;
  };
  on<T extends FrEventName>(type: T, handler: (event: FrEvent<T>) => void): () => void;
}
declare global { interface Window { readonly fr: FrBridge } }
