import { readFile, writeFile, mkdir, readdir } from 'node:fs/promises';
import path from 'node:path';
import { compile } from 'json-schema-to-typescript';

const base = path.resolve('specs/schemas');
const schemas = Object.fromEntries(await Promise.all((await readdir(base)).map(async (file) =>
  [file, JSON.parse(await readFile(path.join(base, file), 'utf8'))])));
const manifest = schemas['ipc-channels.json'];
function deepPartial(value) {
  if (Array.isArray(value)) return value.map(deepPartial);
  if (value === null || typeof value !== 'object') return value;
  if (typeof value.$ref === 'string' && value.$ref.startsWith('#/$defs/')) {
    return deepPartial(configSchema.$defs[value.$ref.split('/').at(-1)]);
  }
  return Object.fromEntries(Object.entries(value).filter(([key]) => key !== 'required')
    .map(([key, item]) => [key, deepPartial(item)]));
}
const configSchema = schemas['app-config.schema.json'];
manifest.$defs.AppConfigPatch = { ...deepPartial(configSchema), $id: undefined,
  title: 'AppConfigPatch', minProperties: 1,
  properties: Object.fromEntries(Object.keys(manifest.$defs.AppConfigPatch.properties)
    .map((key) => [key, deepPartial(configSchema.properties[key])])),
};
const header = '// Generated by pnpm gen. Do not edit.\n';
const outputs = new Map();
const clean = (schema) => JSON.parse(JSON.stringify(schema), (key, value) => {
  if (key === '$id') return undefined;
  return value;
});
const options = { bannerComment: header.trim(), unknownAny: true, additionalProperties: false,
  cwd: base, unreachableDefinitions: true, style: { singleQuote: true },
  $refOptions: { resolve: { freeread: { order: 1,
    canRead: /^https:\/\/freeread\.dev\/schemas\//,
    read: (file) => clean(schemas[new URL(file.url).pathname.split('/').at(-1)]),
  } } },
};
const targets = {
  'doc-anchor-model.schema.json': ['packages/core/src/anchor.generated.ts', 'DocAnchorModel'],
  'annotation.schema.json': ['packages/core/src/annotation.generated.ts', 'Annotation'],
  'meta.schema.json': ['packages/core/src/meta.generated.ts', 'DocMeta'],
  'agent-session.schema.json': ['packages/core/src/agent/session.generated.ts', 'AgentSessionEvent'],
  'agent-permissions.schema.json': ['packages/core/src/agent/permissions.generated.ts', 'AgentPermissions'],
  'app-config.schema.json': ['apps/desktop/src/main/config.generated.ts', 'AppConfig'],
  'parse-request.schema.json': ['packages/parser-protocol/src/generated/parse-request.generated.ts', 'ParseRequest'],
  'parse-result.schema.json': ['packages/parser-protocol/src/generated/parse-result.generated.ts', 'ParseResult'],
};
for (const [file, [target, name]] of Object.entries(targets)) {
  outputs.set(target, await compile({ ...clean(schemas[file]), title: name }, name, options));
}
const payloadSchema = { type: 'object', additionalProperties: false,
  $defs: manifest.$defs, required: Object.keys(manifest.$defs),
  properties: Object.fromEntries(Object.keys(manifest.$defs).map((name) =>
    [name, { $ref: `#/$defs/${name}` }])) };
outputs.set('packages/core/src/ipc-payloads.generated.ts',
  await compile(clean(payloadSchema), 'IpcPayloads', options));
const key = (ref) => ref.$ref.split('/').at(-1);
const channels = manifest.channels;
const events = manifest.events;
const channelNames = channels.map((c) => c.name);
const eventNames = events.map((e) => e.name);
outputs.set('packages/core/src/ipc-channels.generated.ts', header +
  `export const CHANNEL_NAMES = ${JSON.stringify(channelNames)} as const;\n` +
  `export const EVENT_NAMES = ${JSON.stringify(eventNames)} as const;\n` +
  'export type FrChannelName = typeof CHANNEL_NAMES[number];\n' +
  'export type FrEventName = typeof EVENT_NAMES[number];\n');
const domains = [...new Set(channels.map((c) => c.domain))];
const contract = header + "import type { IpcPayloads, FrEventName } from '@freeread/core';\n" +
  "export type ApiResult<T> = { ok: true; data: T } | { ok: false; error: IpcPayloads['ErrorObject'] };\n" +
  'export interface EventPayloads {\n' + events.map((e) =>
    `  '${e.name}': IpcPayloads['${key(e.payload)}'];`).join('\n') + '\n}\n' +
  'export type FrEvent<T extends FrEventName> = { type: T; payload: EventPayloads[T]; ts: number; seq: number };\n' +
  'export interface FrBridge {\n' + domains.map((domain) =>
    `  readonly ${domain}: {\n` + channels.filter((c) => c.domain === domain).map((c) =>
      `    ${c.name.split(':')[2]}(req: IpcPayloads['${key(c.request)}']): Promise<ApiResult<IpcPayloads['${key(c.response)}']>>;`).join('\n') + '\n  };').join('\n') +
  '\n  on<T extends FrEventName>(type: T, handler: (event: FrEvent<T>) => void): () => void;\n}\n' +
  'declare global { interface Window { readonly fr: FrBridge } }\n';
outputs.set('apps/desktop/src/renderer/ipc/client.generated.ts', contract);
outputs.set('apps/desktop/src/preload/bridge.generated.ts', header +
  "import { contextBridge, ipcRenderer } from 'electron';\n" +
  "import type { FrBridge, FrEvent } from '../renderer/ipc/client.generated';\n" +
  "import { AppError } from '@freeread/core';\n" +
  "import type { FrEventName } from '@freeread/core';\n" +
  `const events: readonly string[] = ${JSON.stringify(eventNames)};\n` +
  'const bridge: FrBridge = {\n' + domains.map((domain) =>
    `  ${domain}: {\n` + channels.filter((c) => c.domain === domain).map((c) =>
      `    ${c.name.split(':')[2]}: (req) => ipcRenderer.invoke('${c.name}', req),`).join('\n') + '\n  },').join('\n') +
  '\n  on<T extends FrEventName>(type: T, handler: (event: FrEvent<T>) => void) {\n' +
  "    if (!events.includes(type)) throw new AppError('FR-IPC-001', { category: 'ipc', severity: 'fatal', retryable: false, i18nKey: 'errors.FR-IPC-001' });\n" +
  '    const listener = (_event: unknown, data: FrEvent<T>) => handler(data);\n' +
  '    ipcRenderer.on(type, listener);\n    return () => { ipcRenderer.removeListener(type, listener); };\n  },\n};\n' +
  "contextBridge.exposeInMainWorld('fr', bridge);\n");
outputs.set('apps/desktop/src/main/ipc/registry.generated.ts', header +
  `export const CHANNEL_REGISTRY = ${JSON.stringify(channels, null, 2)} as const;\n`);
outputs.set('apps/desktop/src/main/ipc/schemas.generated.ts', header +
  "import { createValidator } from './validate';\n" +
  'export const IPC_SCHEMAS = {\n' + channels.map((c) =>
    `  '${c.name}': { request: createValidator('${key(c.request)}'), response: createValidator('${key(c.response)}') },`).join('\n') + '\n} as const;\n');
outputs.set('apps/desktop/src/main/ipc/contract-data.generated.ts', header +
  'export const CONTRACT_SCHEMAS: Record<string, unknown>[] = ' + JSON.stringify(Object.values(schemas)) + ';\n');
let drift = false;
for (const [file, content] of outputs) {
  if (process.argv.includes('--check')) {
    let actual;
    try { actual = await readFile(file, 'utf8'); } catch (error) {
      if (error.code !== 'ENOENT') throw error;
    }
    if (actual !== content) { console.error(`Generated drift: ${file}`); drift = true; }
  } else {
    await mkdir(path.dirname(file), { recursive: true });
    await writeFile(file, content);
  }
}
if (drift) process.exitCode = 1;
else console.log(`Schemas: ${outputs.size} outputs, ${channels.length} channels, ${events.length} events`);
