import { execFileSync } from 'node:child_process';
import { readFile, writeFile, readdir } from 'node:fs/promises';
import path from 'node:path';
import { isAllowed } from './license-policy.mjs';

const check = process.argv.indexOf('check');
if (check !== -1) {
  const pkg = process.argv[check + 1];
  if (!pkg || !/^(@[\w.-]+\/)?[\w.-]+(?:@[\w.^~-]+)?$/.test(pkg)) throw new Error('Expected package name');
  const license = execFileSync(process.execPath, [process.env['npm_execpath'], 'view', pkg, 'license', '--json'], { encoding: 'utf8' });
  if (!isAllowed(JSON.parse(license))) throw new Error(`License rejected: ${pkg}`);
  console.log(`License allowed: ${pkg}`);
} else {
  const output = execFileSync(process.execPath, [process.env['npm_execpath'], 'licenses', 'list', '--json'], { encoding: 'utf8', maxBuffer: 20 * 1024 * 1024 });
  const entries = Object.entries(JSON.parse(output)).flatMap(([license, packages]) =>
    packages.flatMap((pkg) => pkg.versions.map((version, index) =>
      ({ ...pkg, license, version, packagePath: pkg.paths[index] }))));
  const rejected = entries.filter((pkg) => !isAllowed(pkg.license));
  if (rejected.length) throw new Error(`License rejected: ${rejected.map((pkg) => `${pkg.name}: ${pkg.license}`).join(', ')}`);
  const sections = [];
  for (const pkg of entries.sort((a, b) => `${a.name}@${a.version}`.localeCompare(`${b.name}@${b.version}`))) {
    const files = await readdir(pkg.packagePath);
    const licenses = files.filter((file) => /^(licen[sc]e|copying|notice)(\.|$)/i.test(file));
    const copyright = (await Promise.all(licenses.map((file) => readFile(path.join(pkg.packagePath, file), 'utf8'))))
      .flatMap((content) => content.split('\n').filter((line) => /copyright|©/i.test(line))).join('\n');
    sections.push(`## ${pkg.name}@${pkg.version}\n\nLicense: ${pkg.license}\n\n${pkg.author ?? ''}\n\nSource: https://registry.npmjs.org/${pkg.name}/-/${pkg.name.split('/').at(-1)}-${pkg.version}.tgz\n\n${copyright}\n`);
  }
  const text = ['# Third-party notices', '', 'Generated by `pnpm license`; includes build/test dependencies.', '', ...sections];
  await writeFile('THIRD_PARTY_NOTICES.md', text.join('\n'));
  const offer = await readFile('SOURCE_OFFER.md', 'utf8');
  if (!offer.includes('source.tar.gz')) throw new Error('Missing corresponding source offer');
  console.log(`License gate: ${entries.length} dependency entries allowed`);
}
