// Generated by pnpm gen. Do not edit.

/**
 * FreeRead 应用配置（%APPDATA%/FreeRead/config.json，Linux 为 ~/.config/FreeRead/config.json）的权威契约。**本文件禁止出现任何密钥/令牌/密码字段**：additionalProperties:false 会在加载时拒绝未知字段，密钥一律存 OS Keychain（服务名 dev.freeread.app，见 specs/05-storage.md §11 PR5）。本地绝对路径只允许出现在本文件的 libraryPath / cachePath。修改字段语义必须 bump schemaVersion（specs/README.md F9）。
 */
export interface AppConfig {
  /**
   * 配置格式版本；字段语义变更时必须 bump 并提供迁移（specs/05-storage.md §8）。
   */
  schemaVersion: 1;
  /**
   * 界面语言；用户可见文案一律走 i18n key（specs/00-conventions.md §1）。
   */
  locale: 'zh-CN' | 'en';
  /**
   * 主题；system 表示跟随操作系统。
   */
  theme: 'light' | 'dark' | 'system';
  /**
   * 知识库根目录绝对路径（默认 ~/FreeRead/library）。全系统唯一允许保存本地绝对路径的配置项之一。
   */
  libraryPath: string;
  /**
   * 缓存根目录绝对路径（页面位图/译文/OCR），可随时清理；容量上限见 BUDGETS.CACHE_MAX_MB。
   */
  cachePath: string;
  reader?: Reader;
  translation?: Translation;
  parser?: Parser;
  privacy?: Privacy;
  sync?: Sync;
}
/**
 * 阅读器排版与显示设置（缺省时使用应用内置默认值，不写入文件）。
 */
export interface Reader {
  /**
   * 正文字体族（CSS font-family 值，仅允许本地已安装字体或随包字体）。
   */
  fontFamily?: string;
  /**
   * 正文字号（px，对应 CSS 变量 --fr-font-size）。
   */
  fontSize?: number;
  /**
   * 行高倍数（无单位，对应 --fr-line-height）。
   */
  lineHeight?: number;
  /**
   * 正文最大宽度（px），用于控制单行字符数（可读性）。
   */
  maxWidth?: number;
  /**
   * 对照模式下是否给译文加下划线以区分原文（无障碍与可读性）。
   */
  showTranslationUnderline?: boolean;
  /**
   * 对照翻译显示模式：dual=原文与译文并排/上下；target-only=仅译文；source-only=仅原文（关闭翻译显示但保留缓存）。
   */
  translationDisplay?: 'dual' | 'target-only' | 'source-only';
  /**
   * 三栏阅读器布局偏好（specs/07-ui-spec.md §3.2/§3.4）。拖拽结束、面板切换、模式切换时节流 500ms 写盘；读取失败回落默认值（不得抛错阻塞渲染）。
   */
  layout?: {
    /**
     * 左栏（大纲/缩略图/标签）宽度 px，默认 260。
     */
    leftWidth?: number;
    /**
     * 右栏（笔记/翻译/AI）宽度 px，默认 360。
     */
    rightWidth?: number;
    /**
     * 左栏是否收起（≤1024px 断点会自动收起）。
     */
    leftCollapsed?: boolean;
    /**
     * 右栏是否收起（≤1280px 断点会自动收起）。
     */
    rightCollapsed?: boolean;
  };
}
/**
 * 翻译 Provider 与术语表设置；API key 不在本对象内，存 OS Keychain。
 */
export interface Translation {
  /**
   * 翻译后端：ollama=本地（默认推荐，零上传）；openai-compatible=用户自带 baseUrl + Key；none=仅词典式划词降级。
   */
  provider: 'ollama' | 'openai-compatible' | 'none';
  /**
   * 模型名，如 'qwen2.5:7b'（ollama）或 'deepseek-chat'（openai-compatible）；provider='none' 时省略。
   */
  model?: string;
  /**
   * OpenAI 兼容服务的基址（仅 http/https，默认 http://127.0.0.1:11434 用于 ollama）；出站仍必须经 NetGuard 白名单（specs/09-fetch-compliance.md）。
   */
  baseUrl?: string;
  /**
   * 目标语言（BCP 47），决定 translation/<lang>.jsonl 的文件名，如 'zh-CN'。
   */
  targetLang: string;
  /**
   * 术语表（GlossaryTerm[]）：翻译时必须命中，未命中即视为不合规输出；可全局共享也可按 docId 限定。
   *
   * @maxItems 2048
   */
  glossary?: GlossaryTerm[];
}
/**
 * 单条术语（specs/README.md §3 的 GlossaryTerm）。
 *
 * This interface was referenced by `AppConfig`'s JSON-Schema
 * via the `definition` "GlossaryTerm".
 */
export interface GlossaryTerm {
  /**
   * 源语言术语原文（Unicode NFC）。
   */
  source: string;
  /**
   * 目标语言固定译法。
   */
  target: string;
  /**
   * 匹配是否区分大小写（默认 false；中文等无大小写语言忽略此字段）。
   */
  caseSensitive?: boolean;
}
/**
 * 版面解析设置（引擎选择、OCR、模型下载授权）。
 */
export interface Parser {
  /**
   * 版面解析引擎：docling 默认；marker 用于表格/公式密集兜底；rule 为无 sidecar 时的纯 JS 降级；auto 由应用按可用性与文档特征选择（同一文档只用一个引擎）。
   */
  engine: 'docling' | 'marker' | 'rule' | 'auto';
  /**
   * 是否对无文本层（< 20 字符/页）的扫描件启用 OCR（PaddleOCR 优先，Tesseract 兜底）。
   */
  ocr: boolean;
  /**
   * 是否同意按需下载解析/OCR 模型权重（含体积与 SHA256 校验提示）；false 时只使用本地已有模型或 rule 降级。
   */
  consentToDownloadModels?: boolean;
}
/**
 * 隐私开关；默认最保守（telemetry 恒为 false）。
 */
export interface Privacy {
  /**
   * 遥测开关：**恒为 false**（本项目不收集任何使用数据，schema 层直接禁止开启）。
   */
  telemetry: false;
  /**
   * 崩溃上报（默认关闭；启用时仅上传脱敏堆栈，不含文档内容与路径，ADR-12）。
   */
  crashReports?: boolean;
}
/**
 * 同步设置（ADR-09：V1 由用户自选同步盘或 WebDAV，应用只做文件级冲突检测）。
 */
export interface Sync {
  /**
   * 同步方式：none=不同步；webdav=用户自建 WebDAV；folder=用户自选同步盘目录（Syncthing/OneDrive 等）。
   */
  provider: 'none' | 'webdav' | 'folder';
  /**
   * WebDAV 服务地址（仅 provider='webdav' 时有效）。
   */
  url?: string;
  /**
   * WebDAV 用户名（非敏感字段）；对应密码存 OS Keychain，键为 'sync:webdav:<username>'。
   */
  username?: string;
}
/**
 * 重排视图的排版参数；全部为显示层参数，不写入 blocks.json（模型中不存缩放，specs/03-anchor-model.md §3）。
 *
 * This interface was referenced by `AppConfig`'s JSON-Schema
 * via the `definition` "Reader".
 */
export interface Reader1 {
  /**
   * 正文字体族（CSS font-family 值，仅允许本地已安装字体或随包字体）。
   */
  fontFamily?: string;
  /**
   * 正文字号（px，对应 CSS 变量 --fr-font-size）。
   */
  fontSize?: number;
  /**
   * 行高倍数（无单位，对应 --fr-line-height）。
   */
  lineHeight?: number;
  /**
   * 正文最大宽度（px），用于控制单行字符数（可读性）。
   */
  maxWidth?: number;
  /**
   * 对照模式下是否给译文加下划线以区分原文（无障碍与可读性）。
   */
  showTranslationUnderline?: boolean;
  /**
   * 对照翻译显示模式：dual=原文与译文并排/上下；target-only=仅译文；source-only=仅原文（关闭翻译显示但保留缓存）。
   */
  translationDisplay?: 'dual' | 'target-only' | 'source-only';
  /**
   * 三栏阅读器布局偏好（specs/07-ui-spec.md §3.2/§3.4）。拖拽结束、面板切换、模式切换时节流 500ms 写盘；读取失败回落默认值（不得抛错阻塞渲染）。
   */
  layout?: {
    /**
     * 左栏（大纲/缩略图/标签）宽度 px，默认 260。
     */
    leftWidth?: number;
    /**
     * 右栏（笔记/翻译/AI）宽度 px，默认 360。
     */
    rightWidth?: number;
    /**
     * 左栏是否收起（≤1024px 断点会自动收起）。
     */
    leftCollapsed?: boolean;
    /**
     * 右栏是否收起（≤1280px 断点会自动收起）。
     */
    rightCollapsed?: boolean;
  };
}
/**
 * 翻译 Provider 配置（specs/08-translation.md）。**任何 apiKey / token / secret 字段一律不得出现**。
 *
 * This interface was referenced by `AppConfig`'s JSON-Schema
 * via the `definition` "Translation".
 */
export interface Translation1 {
  /**
   * 翻译后端：ollama=本地（默认推荐，零上传）；openai-compatible=用户自带 baseUrl + Key；none=仅词典式划词降级。
   */
  provider: 'ollama' | 'openai-compatible' | 'none';
  /**
   * 模型名，如 'qwen2.5:7b'（ollama）或 'deepseek-chat'（openai-compatible）；provider='none' 时省略。
   */
  model?: string;
  /**
   * OpenAI 兼容服务的基址（仅 http/https，默认 http://127.0.0.1:11434 用于 ollama）；出站仍必须经 NetGuard 白名单（specs/09-fetch-compliance.md）。
   */
  baseUrl?: string;
  /**
   * 目标语言（BCP 47），决定 translation/<lang>.jsonl 的文件名，如 'zh-CN'。
   */
  targetLang: string;
  /**
   * 术语表（GlossaryTerm[]）：翻译时必须命中，未命中即视为不合规输出；可全局共享也可按 docId 限定。
   *
   * @maxItems 2048
   */
  glossary?: GlossaryTerm[];
}
/**
 * 解析设置（specs/04-parser-sidecar.md）。
 *
 * This interface was referenced by `AppConfig`'s JSON-Schema
 * via the `definition` "Parser".
 */
export interface Parser1 {
  /**
   * 版面解析引擎：docling 默认；marker 用于表格/公式密集兜底；rule 为无 sidecar 时的纯 JS 降级；auto 由应用按可用性与文档特征选择（同一文档只用一个引擎）。
   */
  engine: 'docling' | 'marker' | 'rule' | 'auto';
  /**
   * 是否对无文本层（< 20 字符/页）的扫描件启用 OCR（PaddleOCR 优先，Tesseract 兜底）。
   */
  ocr: boolean;
  /**
   * 是否同意按需下载解析/OCR 模型权重（含体积与 SHA256 校验提示）；false 时只使用本地已有模型或 rule 降级。
   */
  consentToDownloadModels?: boolean;
}
/**
 * 隐私开关；除 telemetry 外均为用户可选项。
 *
 * This interface was referenced by `AppConfig`'s JSON-Schema
 * via the `definition` "Privacy".
 */
export interface Privacy1 {
  /**
   * 遥测开关：**恒为 false**（本项目不收集任何使用数据，schema 层直接禁止开启）。
   */
  telemetry: false;
  /**
   * 崩溃上报（默认关闭；启用时仅上传脱敏堆栈，不含文档内容与路径，ADR-12）。
   */
  crashReports?: boolean;
}
/**
 * 同步设置（ADR-09）。**密码/应用密码/token 不得写入 config.json**，必须存 OS Keychain（账号名 provider:<name>）。
 *
 * This interface was referenced by `AppConfig`'s JSON-Schema
 * via the `definition` "Sync".
 */
export interface Sync1 {
  /**
   * 同步方式：none=不同步；webdav=用户自建 WebDAV；folder=用户自选同步盘目录（Syncthing/OneDrive 等）。
   */
  provider: 'none' | 'webdav' | 'folder';
  /**
   * WebDAV 服务地址（仅 provider='webdav' 时有效）。
   */
  url?: string;
  /**
   * WebDAV 用户名（非敏感字段）；对应密码存 OS Keychain，键为 'sync:webdav:<username>'。
   */
  username?: string;
}
