// Generated by pnpm gen. Do not edit.

/**
 * 项目级 Agent 工具权限表（projects/<projectId>/permissions.json）。权威定义见 specs/14-agent.md §5。
 */
export interface AgentPermissions {
  schemaVersion: 1;
  /**
   * ULID
   */
  projectId: string;
  /**
   * 工具级权限规则；未列出的工具使用其 defaultRule（见 14 §4.1）
   */
  rules: {
    /**
     * 工具名，如 workspace_write
     */
    tool: string;
    rule: 'always' | 'once' | 'ask' | 'deny';
    updatedAt: number;
  }[];
}
