// Generated by pnpm gen. Do not edit.

/**
 * Agent 会话事件流单行（sessions/<sessionId>.jsonl，append-only）。权威定义见 specs/14-agent.md §8。
 */
export type AgentSessionEvent =
  MessageEvent | ToolCallEvent | ToolResultEvent | PermissionEvent | RunEvent | ErrorEvent;
export type MessageEvent = Base & {
  type: 'message';
  seq: number;
  at: number;
  role: 'user' | 'assistant';
  text: string;
  tokens?: {
    in?: number;
    out?: number;
  };
};
export type ToolCallEvent = Base & {
  type: 'tool_call';
  seq: number;
  at: number;
  callId: string;
  tool: string;
  /**
   * 参数的 sha256；不落原文（AG-8）
   */
  argsHash: string;
  /**
   * 可读摘要，不含敏感内容
   */
  argsSummary: string;
};
export type ToolResultEvent = Base & {
  type: 'tool_result';
  seq: number;
  at: number;
  callId: string;
  ok: boolean;
  summary: string;
  errorCode?: string;
  durationMs: number;
};
export type PermissionEvent = Base & {
  type: 'permission';
  seq: number;
  at: number;
  callId: string;
  tool: string;
  /**
   * deny 含用户拒绝与 120s 超时兜底
   */
  decision: 'always' | 'once' | 'ask' | 'deny';
  /**
   * false 表示超时自动判定
   */
  byUser?: boolean;
};
export type RunEvent = Base & {
  type: 'run';
  seq: number;
  at: number;
  runId?: string;
  state: 'started' | 'finished' | 'canceled' | 'failed';
  steps: number;
  toolCalls: number;
  reason?: string;
  /**
   * finish 工具的引用列表（AG-10）
   */
  citations?: {
    callId: string;
    docId?: string;
    note?: string;
  }[];
};
export type ErrorEvent = Base & {
  type: 'error';
  seq: number;
  at: number;
  code: string;
  message: string;
};

export interface Base {
  type: string;
  /**
   * 会话内单调递增序号（从 1 开始），用于增量拉取
   */
  seq: number;
  /**
   * UTC 毫秒
   */
  at: number;
}
